module.exports = {
  INVALID_REQUEST: {
    STATUS: 400,
    DEFAULT_MESSAGE: "INVALID REQUEST SENT",
  },

  INVALID_LOGIN_REQUEST: {
    STATUS: 400,
    DEFAULT_MESSAGE: "User email or password in missing or incorrect",
  },
  FORBIDDEN: {
    STATUS: 403,
    DEFAULT_MESSAGE: "FORBIDDEN REQUEST",
  },

  NOT_FOUND: {
    STATUS: 404,
    DEFAULT_MESSAGE: "RESOURCE NOT FOUND ",
  },
  DEFAULT_ERROR: {
    STATUS: 500,
    DEFAULT_MESSAGE: "AN ERROR HAS OCCURED ON THE SERVER",
  },
};
